src/main/java/com/bluelotussoftware/example/model/DiscountCode.java
/*
 * Copyright 2011-2013 Blue Lotus Software, LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * $Id$
 */
package com.bluelotussoftware.example.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author John Yeary <jyeary@bluelotussoftware.com>
 * @version 1.0
 */
@Entity
@Table(name = "DISCOUNT_CODE")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "DiscountCode.findAll", query = "SELECT d FROM DiscountCode d"),
    @NamedQuery(name = "DiscountCode.findByDiscountCode", query = "SELECT d FROM DiscountCode d WHERE d.discountCode = :discountCode"),
    @NamedQuery(name = "DiscountCode.findByRate", query = "SELECT d FROM DiscountCode d WHERE d.rate = :rate")})
public class DiscountCode implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "DISCOUNT_CODE")
    private Character discountCode;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "RATE")
    private BigDecimal rate;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "discountCode")
    private Collection<Customer> customerCollection;

    public DiscountCode() {
    }

    public DiscountCode(Character discountCode) {
        this.discountCode = discountCode;
    }

    public Character getDiscountCode() {
        return discountCode;
    }

    public void setDiscountCode(Character discountCode) {
        this.discountCode = discountCode;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    @XmlTransient
    public Collection<Customer> getCustomerCollection() {
        return customerCollection;
    }

    public void setCustomerCollection(Collection<Customer> customerCollection) {
        this.customerCollection = customerCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (discountCode != null ? discountCode.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof DiscountCode)) {
            return false;
        }
        DiscountCode other = (DiscountCode) object;
        if ((this.discountCode == null && other.discountCode != null) || (this.discountCode != null && !this.discountCode.equals(other.discountCode))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.bluelotussoftware.example.model.DiscountCode[ discountCode=" + discountCode + " ]";
    }
}

src/main/java/com/bluelotussoftware/example/jsf/ChartBean.java
/*
 * Copyright 2011-2013 Blue Lotus Software, LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * $Id$
 */
package com.bluelotussoftware.example.jsf;

import com.bluelotussoftware.example.model.Customer;
import com.bluelotussoftware.example.model.Product;
import com.bluelotussoftware.example.model.PurchaseOrder;
import com.bluelotussoftware.example.ssb.CustomerFacade;
import com.bluelotussoftware.example.ssb.ProductFacade;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.imageio.ImageIO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jsflot.components.FlotChartRendererData;
import org.jsflot.xydata.XYDataList;
import org.jsflot.xydata.XYDataPoint;
import org.jsflot.xydata.XYDataSetCollection;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.chart.BubbleChartModel;
import org.primefaces.model.chart.BubbleChartSeries;
import org.primefaces.model.chart.CartesianChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.MeterGaugeChartModel;
import org.primefaces.model.chart.PieChartModel;

/**
 *
 * @author John Yeary <jyeary@bluelotussoftware.com>
 * @version 1.0
 */
@ManagedBean
@RequestScoped
public class ChartBean {

    private Map<Integer, Map<String, Number>> CustomerPurchasesByYearTotals = new HashMap<Integer, Map<String, Number>>();
    private double totalSales;
    //PrimeFaces
    private PieChartModel pieChartModel;
    private CartesianChartModel cartesianChartModel;
    private BubbleChartModel bubbleChartModel;
    private MeterGaugeChartModel meterGaugeChartModel;
    //JSFlot
    private XYDataList series1DataList = new XYDataList();
    private XYDataList series2DataList = new XYDataList();
    private XYDataList series3DataList = new XYDataList();
    private FlotChartRendererData chartData;
    private StreamedContent streamedContent;
    @EJB
    private CustomerFacade cf;
    @EJB
    private ProductFacade pf;

    /**
     * Creates a new instance of ChartBean
     */
    public ChartBean() {
    }

    @PostConstruct
    private void initialize() throws IOException {
        bubbleChartModel = new BubbleChartModel();
        cartesianChartModel = new CartesianChartModel();
        pieChartModel = new PieChartModel(getSalesByCustomer());
        createCartesianChartModel();
        createBubbleModel();
        createMeterGaugeModel();

        //JFreeChart  
        JFreeChart jfreechart = ChartFactory.createPieChart("Products", getPartsDataset(), true, false, false);
        PiePlot pp = (PiePlot)jfreechart.getPlot();
        pp.setLabelGenerator(null);
        String path = FacesContext.getCurrentInstance().getExternalContext().getRealPath("/");
        File chartFile = new File(path + "dynamichart.png");
        ChartUtilities.saveChartAsPNG(chartFile, jfreechart, 600, 400);
        streamedContent = new DefaultStreamedContent(new FileInputStream(chartFile), "image/png");


        chartData = new FlotChartRendererData();

        for (int i = 0; i <= 100; i++) {
            NumberFormat nf = NumberFormat.getNumberInstance();
            nf.setMaximumFractionDigits(3);

            series1DataList.addDataPoint(new XYDataPoint(i, Math.random() * 10, "Point: " + i));
            series2DataList.addDataPoint(new XYDataPoint(i, Math.random() * 10, "Point: " + i));
            series3DataList.addDataPoint(new XYDataPoint(i, Math.random() * 10));
        }
        series1DataList.setLabel("Series 1");
        series2DataList.setLabel("Series 2");
        series3DataList.setLabel("Series 3");
    }

    public PieChartModel getPieChartModel() {
        return pieChartModel;
    }

    public BubbleChartModel getBubbleChartModel() {
        return bubbleChartModel;
    }

    public CartesianChartModel getCartesianChartModel() {
        return cartesianChartModel;
    }

    public MeterGaugeChartModel getMeterGaugeChartModel() {
        return meterGaugeChartModel;
    }

    private Map<String, Number> getSalesByCustomer() {
        Map<String, Number> salesByCustomer = new HashMap<String, Number>();

        List<Customer> customers = cf.findAll();

        for (Customer c : customers) {
            double sales = 0.0;
            for (PurchaseOrder p : c.getPurchaseOrderCollection()) {
                sales += p.getProductId().getPurchaseCost().doubleValue() * p.getQuantity();
            }
            salesByCustomer.put(c.getName(), sales);
        }
        return salesByCustomer;
    }

    private void createCartesianChartModel() {
        Calendar cal = Calendar.getInstance();
        List<Customer> customers = cf.findAll();
        List<Integer> customersLessThan10K = new ArrayList<Integer>();
        List<Integer> customersGreaterThan10K = new ArrayList<Integer>();
        Collections.sort(customers);

        for (Customer c : customers) {
            double sales = 0.0;

            for (PurchaseOrder p : c.getPurchaseOrderCollection()) {
                cal.setTime(p.getSalesDate());
                double vx = p.getProductId().getPurchaseCost().doubleValue() * p.getQuantity();
                addOrUpdate(c.getCustomerId(), String.valueOf(cal.get(Calendar.YEAR)), vx);
                sales += vx;
            }

            if (sales < 10000.00) {
                customersLessThan10K.add(c.getCustomerId());
            } else {
                customersGreaterThan10K.add(c.getCustomerId());
            }
            totalSales += sales;
        }

        Map<Object, Number> lt10k = new HashMap<Object, Number>();
        Map<Object, Number> gt10k = new HashMap<Object, Number>();

        for (Integer i : customersLessThan10K) {
            populateMap(lt10k, CustomerPurchasesByYearTotals.get(i));
        }

        for (Integer i : customersGreaterThan10K) {
            populateMap(gt10k, CustomerPurchasesByYearTotals.get(i));
        }

        ChartSeries customersLessThan10k = new ChartSeries("Customers with Sales < 10K");
        customersLessThan10k.setData(lt10k);
        ChartSeries customersGreaterThan10k = new ChartSeries("Customers with Sales > 10K");
        customersGreaterThan10k.setData(gt10k);
        cartesianChartModel.addSeries(customersLessThan10k);
        cartesianChartModel.addSeries(customersGreaterThan10k);
    }

    private void addOrUpdate(Integer customerId, String year, Number value) {
        Map<String, Number> map = CustomerPurchasesByYearTotals.get(customerId);

        if (map == null) {
            map = new HashMap<String, Number>();
            CustomerPurchasesByYearTotals.put(customerId, map);
        }
        Number n = map.get(year);

        if (n == null) {
            map.put(year, value);
        } else {
            map.put(year, (map.get(year).doubleValue() + value.doubleValue()));
        }
    }

    private void populateMap(Map<Object, Number> map, Map<String, Number> data) {
        if (data == null) {
            return;
        }
        for (String key : data.keySet()) {
            Number n = map.get((Object) key);
            if (n == null) {
                map.put((Object) key, data.get(key));
            } else {
                map.put((Object) key, n.doubleValue() + data.get(key).doubleValue());
            }
        }
    }

    private void createBubbleModel() {
        for (Product p : pf.findAll()) {
            bubbleChartModel.add(new BubbleChartSeries(
                    p.getDescription(), //label
                    p.getQuantityOnHand(), // x
                    p.getMarkup().intValue(), //y 
                    p.getPurchaseCost().intValue() //radius
                    ));
        }
    }

    private void createMeterGaugeModel() {
        List<Number> intervals = new ArrayList<Number>() {
            {
                add(200000);
                add(400000);
                add(600000);
                add(800000);
            }
        };
//        meterGaugeChartModel = new MeterGaugeChartModel("Sales", totalSales, intervals); //PrimeFaces 3.3+
        meterGaugeChartModel = new MeterGaugeChartModel(Double.valueOf(totalSales), intervals); //PrimeFaces 3.4+
    }

    public XYDataSetCollection getChartSeries() {
        XYDataSetCollection collection = new XYDataSetCollection();
        XYDataList currentSeries1DataList = new XYDataList();
        XYDataList currentSeries2DataList = new XYDataList();
        XYDataList currentSeries3DataList = new XYDataList();

        for (int i = 0; i <= 10; i++) {
            long startTime = 1196463600000l;

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:rich="http://richfaces.org/rich">
    <h:head>
        <title>RichFaces (F/OSS) Charting Options</title>
    </h:head>
    <h:body>
        <o:form>
            <rich:panel header="RichFaces (F/OSS) Charting Options">
                <h:link outcome="primefaces" value="PrimeFaces Chart Examples"/>
                <br/>
                <h:link outcome="jsflot" value="JSFlot Chart Examples"/>
                <br/>
                <h:link outcome="jfreechart" value="JFreeChart Chart Examples"/>
            </rich:panel>
        </o:form>
    </h:body>
</html>


src/main/webapp/jfreechart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:rich="http://richfaces.org/rich">
    <h:head>
        <title>JFreeChart 3D Pie</title>
    </h:head>
    <h:body>
        <o:form>
            <rich:panel header="JFreeChart 3D Pie">
                <a4j:mediaOutput element="img"
                                 expires="#{now}"
                                 cacheable="#{false}"                 
                                 createContent="#{chartBean.generateChartMethod}"
                                 mimeType="image/png" />
            </rich:panel>
        </o:form>
    </h:body>
</html>


src/main/webapp/jsflot.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:jsflot="http://www.jsflot.org/taglib/jsflot"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:rich="http://richfaces.org/rich">
    <h:head>
        <title>JSFLot Chart Examples</title>
        <jsflot:resources/>
    </h:head>
    <h:body>
        <o:form>
            <rich:panel header="JSFlot Bar Chart">
                <jsflot:flotChart
                    value="#{chartBean.chartSeries}" 
                    chartType="bar"
                    showDataPoints="true"
                    showLines="true"
                    title="Line Chart"
                    chartZoomable="true"
                    markers="true"
                    spreadsheet="true"
                    width="100%"
                    />
            </rich:panel>
            <rich:panel header="JSFlot Line Chart">
                <jsflot:flotChart 
                    value="#{chartBean.chartSeries}" 
                    chartType="line"
                    showDataPoints="true"
                    showLines="true"
                    title="Line Chart"
                    chartZoomable="true"
                    markers="true"
                    spreadsheet="true"
                    width="100%"
                    />
            </rich:panel>
            <rich:panel header="JSFlot Stacked Bar Chart">
                <jsflot:flotChart
                    value="#{chartBean.chartSeries}" 
                    chartType="stackedBar"
                    showDataPoints="true"
                    showLines="true"
                    title="Line Chart"
                    chartZoomable="true"
                    markers="true"
                    spreadsheet="true"
                    width="100%"
                    />
            </rich:panel>
        </o:form>
    </h:body>
</html>


src/main/webapp/primefaces.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:rich="http://richfaces.org/rich"
      >
    <h:head id="head1">
        <title>PrimeFaces Chart Examples</title>
    </h:head>
    <h:body id="body1">
        <o:form id="form1">

            <rich:panel id="areaChartPanel" header="PrimeFaces Area Chart">
                <p:lineChart id="stacked" value="#{chartBean.cartesianChartModel}" 
                             legendPosition="nw" stacked="true" fill="true" 
                             xaxisLabel="Year" yaxisLabel="Profits($)"
                             title="Customers Grouped by Total Sales Purchases" 
                             minX="2005"
                             maxX="2013"
                             minY="0"
                             maxY="110000"
                             />
            </rich:panel>

            <rich:panel id="bubbleChartPanel" header="PrimeFaces Bubble Chart">
                <p:bubbleChart id="custom" value="#{chartBean.bubbleChartModel}" 
                               shadow="false"
                               bubbleGradients="true" showLabels="false" bubbleAlpha="100"  
                               title="Part Data" 
                               xaxisAngle="-50" yaxisAngle="50"/>
            </rich:panel>

            <rich:panel id="meterGaugePanel" header="PrimeFaces Meter Gauge Chart">
                <p:meterGaugeChart id="meterGaugeChart" value="#{chartBean.meterGaugeChartModel}" 
                                   showTickLabels="true" labelHeightAdjust="110"  
                                   intervalOuterRadius="130" 
                                   seriesColors="cc6666,E7E658,93b75f,66cc66" title="Sales" label="Total" />  
            </rich:panel>

            <rich:panel id="pieChartPanel" header="PrimeFaces Pie Chart">
                <p:pieChart id="pieChart1" value="#{chartBean.pieChartModel}" showDataLabels="true" />
            </rich:panel>

            <rich:panel id="static3DPieChart" header="PrimeFaces JFreeChart 3D Pie Chart">
                <p:graphicImage value="#{chartBean.streamedContent}" />  
            </rich:panel>
        </o:form>
    </h:body>
</html>